
### upload file
POST http://localhost:8080/upload?name='file.log'&file='c:/users/nec/DumpStack.log'
Content-Type: multipart/form-data; boundary=WebAppBoundary



### addBand
POST http://localhost:8080/addband
Content-Type: application/x-www-form-urlencoded

bandName=test&country=test


### get
GET http://localhost:8080/test

